[package]
name = "check-size"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
noto-sans-mono-bitmap = { path = "../../", features = ["all"] }
