name: Check codegen

on: [ merge_group, push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check that the codegen helper generates the exact same sources that are
  # currently checked in.
  check_codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.56.1 # MSRV for library consumers
      - name: generate crate
        run: ./codegen_n_build.sh
      - name: check diff crate
        run: git diff --quiet
